// Core — generated by @web-kits/audio (do not edit)
// patch: Core
import type { SoundDefinition, SoundPatch } from "@web-kits/audio";

export const click: SoundDefinition = {
  envelope: { attack: 0, decay: 0.06, release: 0.02, sustain: 0 },
  gain: 0.25,
  source: {
    fm: { depth: 80, ratio: 0.5 },
    frequency: { end: 700, start: 200 },
    type: "sine",
  },
};
export const tap: SoundDefinition = {
  envelope: { attack: 0, decay: 0.015, release: 0.005, sustain: 0 },
  gain: 0.2,
  source: { fm: { depth: 100, ratio: 0.5 }, frequency: 1300, type: "sine" },
};
export const keyPress: SoundDefinition = {
  envelope: { attack: 0, decay: 0.012, release: 0.004, sustain: 0 },
  gain: 0.18,
  source: { fm: { depth: 80, ratio: 0.5 }, frequency: 1300, type: "sine" },
};
export const checkbox: SoundDefinition = {
  envelope: { attack: 0, decay: 0.05, release: 0.015, sustain: 0 },
  gain: 0.22,
  source: {
    fm: { depth: 60, ratio: 0.5 },
    frequency: { end: 800, start: 250 },
    type: "sine",
  },
};
export const radio: SoundDefinition = {
  envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
  gain: 0.2,
  source: {
    fm: { depth: 50, ratio: 0.5 },
    frequency: { end: 900, start: 300 },
    type: "sine",
  },
};
export const tick: SoundDefinition = {
  envelope: { attack: 0, decay: 0.01, release: 0.004, sustain: 0 },
  gain: 0.15,
  source: { fm: { depth: 60, ratio: 0.5 }, frequency: 1500, type: "sine" },
};
export const scrollSnap: SoundDefinition = {
  envelope: { attack: 0, decay: 0.008, release: 0.003, sustain: 0 },
  gain: 0.08,
  source: { fm: { depth: 50, ratio: 0.5 }, frequency: 1400, type: "sine" },
};
export const focus: SoundDefinition = {
  envelope: { attack: 0, decay: 0.02, release: 0.008, sustain: 0 },
  gain: 0.06,
  source: { fm: { depth: 40, ratio: 0.5 }, frequency: 1300, type: "sine" },
};
export const blur: SoundDefinition = {
  envelope: { attack: 0, decay: 0.018, release: 0.008, sustain: 0 },
  gain: 0.04,
  source: { fm: { depth: 30, ratio: 0.5 }, frequency: 1100, type: "sine" },
};
export const toggleOn: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.012, release: 0.004, sustain: 0 },
      gain: 0.2,
      source: { frequency: 2093, type: "sine" },
    },
    {
      delay: 0.025,
      envelope: { attack: 0, decay: 0.012, release: 0.004, sustain: 0 },
      gain: 0.2,
      source: { frequency: 3136, type: "sine" },
    },
  ],
};
export const toggleOff: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.012, release: 0.004, sustain: 0 },
      gain: 0.2,
      source: { frequency: 3136, type: "sine" },
    },
    {
      delay: 0.025,
      envelope: { attack: 0, decay: 0.012, release: 0.004, sustain: 0 },
      gain: 0.2,
      source: { frequency: 2093, type: "sine" },
    },
  ],
};
export const hover: SoundDefinition = {
  envelope: { attack: 0.005, decay: 0.015, release: 0.008, sustain: 0 },
  gain: 0.04,
  source: { frequency: 1300, type: "sine" },
};
export const select: SoundDefinition = {
  envelope: { attack: 0, decay: 0.05, release: 0.015, sustain: 0 },
  gain: 0.2,
  source: { fm: { depth: 60, ratio: 0.5 }, frequency: 1400, type: "sine" },
};
export const deselect: SoundDefinition = {
  envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
  gain: 0.16,
  source: { fm: { depth: 60, ratio: 0.5 }, frequency: 1200, type: "sine" },
};
export const pop: SoundDefinition = {
  envelope: { attack: 0, decay: 0.08, release: 0.025, sustain: 0 },
  gain: 0.25,
  source: { frequency: { end: 150, start: 400 }, type: "sine" },
};
export const boop: SoundDefinition = {
  envelope: { attack: 0, decay: 0.1, release: 0.03, sustain: 0 },
  gain: 0.2,
  source: {
    fm: { depth: 40, ratio: 0.5 },
    frequency: { end: 250, start: 600 },
    type: "sine",
  },
};
export const bounce: SoundDefinition = {
  envelope: { attack: 0, decay: 0.12, release: 0.04, sustain: 0 },
  gain: 0.22,
  source: { frequency: { end: 180, start: 350 }, type: "sine" },
};
export const spring: SoundDefinition = {
  envelope: { attack: 0, decay: 0.15, release: 0.05, sustain: 0.03 },
  gain: 0.18,
  source: {
    fm: { depth: 50, ratio: 0.5 },
    frequency: { end: 900, start: 400 },
    type: "sine",
  },
};
export const expand: SoundDefinition = {
  envelope: { attack: 0.003, decay: 0.1, release: 0.04, sustain: 0.02 },
  gain: 0.12,
  source: { frequency: { end: 700, start: 500 }, type: "sine" },
};
export const collapse: SoundDefinition = {
  envelope: { attack: 0.003, decay: 0.1, release: 0.04, sustain: 0.02 },
  gain: 0.12,
  source: { frequency: { end: 500, start: 700 }, type: "sine" },
};
export const success: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0.003, decay: 0.3, release: 0.1, sustain: 0.06 },
      gain: 0.16,
      source: { frequency: 523, type: "sine" },
    },
    {
      delay: 0.07,
      envelope: { attack: 0.003, decay: 0.28, release: 0.1, sustain: 0.05 },
      gain: 0.14,
      source: { frequency: 659, type: "sine" },
    },
    {
      delay: 0.14,
      envelope: { attack: 0.003, decay: 0.32, release: 0.12, sustain: 0.06 },
      gain: 0.15,
      source: { frequency: { end: 880, start: 784 }, type: "sine" },
    },
  ],
};
export const complete: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0.003, decay: 0.35, release: 0.1, sustain: 0.05 },
      gain: 0.15,
      source: { frequency: 523, type: "sine" },
    },
    {
      delay: 0.015,
      envelope: { attack: 0.003, decay: 0.35, release: 0.1, sustain: 0.05 },
      gain: 0.13,
      source: { frequency: 659, type: "sine" },
    },
    {
      delay: 0.03,
      envelope: { attack: 0.003, decay: 0.35, release: 0.1, sustain: 0.05 },
      gain: 0.12,
      source: { frequency: 784, type: "sine" },
    },
    {
      delay: 0.045,
      envelope: { attack: 0.003, decay: 0.3, release: 0.12, sustain: 0.04 },
      gain: 0.1,
      source: { frequency: { end: 1175, start: 1046 }, type: "sine" },
    },
  ],
};
export const levelUp: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0.003, decay: 0.25, release: 0.1, sustain: 0.06 },
      gain: 0.15,
      source: { frequency: 440, type: "sine" },
    },
    {
      delay: 0.07,
      envelope: { attack: 0.003, decay: 0.25, release: 0.1, sustain: 0.05 },
      gain: 0.14,
      source: { frequency: 554, type: "sine" },
    },
    {
      delay: 0.14,
      envelope: { attack: 0.003, decay: 0.28, release: 0.1, sustain: 0.05 },
      gain: 0.13,
      source: { frequency: 660, type: "sine" },
    },
    {
      delay: 0.21,
      envelope: { attack: 0.003, decay: 0.22, release: 0.12, sustain: 0.04 },
      gain: 0.08,
      source: { frequency: { end: 990, start: 880 }, type: "sine" },
    },
  ],
};
export const confetti: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0.002, decay: 0.18, release: 0.08, sustain: 0.04 },
      gain: 0.14,
      source: { frequency: 523, type: "sine" },
    },
    {
      delay: 0.06,
      envelope: { attack: 0.002, decay: 0.18, release: 0.08, sustain: 0.04 },
      gain: 0.14,
      source: { frequency: 659, type: "sine" },
    },
    {
      delay: 0.12,
      envelope: { attack: 0.002, decay: 0.18, release: 0.08, sustain: 0.03 },
      gain: 0.12,
      source: { frequency: 784, type: "sine" },
    },
    {
      delay: 0.18,
      envelope: { attack: 0.002, decay: 0.2, release: 0.1, sustain: 0.03 },
      gain: 0.1,
      source: { frequency: { end: 1175, start: 1047 }, type: "sine" },
    },
  ],
};
export const save: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.1, release: 0.04, sustain: 0.03 },
      gain: 0.14,
      source: { frequency: { end: 1046, start: 880 }, type: "sine" },
    },
    {
      delay: 0.08,
      envelope: { attack: 0, decay: 0.1, release: 0.04, sustain: 0.02 },
      gain: 0.1,
      source: { frequency: { end: 1175, start: 1046 }, type: "sine" },
    },
  ],
};
export const ding: SoundDefinition = {
  effects: [{ type: "reverb", decay: 0.8, damping: 0.6, mix: 0.15 }],
  envelope: { attack: 0, decay: 0.6, release: 0.25, sustain: 0.04 },
  gain: 0.18,
  source: { fm: { depth: 300, ratio: 3.5 }, frequency: 880, type: "sine" },
};
export const notification: SoundDefinition = {
  layers: [
    {
      effects: [{ type: "reverb", decay: 0.6, damping: 0.6, mix: 0.12 }],
      envelope: { attack: 0, decay: 0.4, release: 0.15, sustain: 0.04 },
      gain: 0.16,
      source: { fm: { depth: 150, ratio: 1.5 }, frequency: 780, type: "sine" },
    },
    {
      delay: 0.1,
      effects: [{ type: "reverb", decay: 0.6, damping: 0.6, mix: 0.12 }],
      envelope: { attack: 0, decay: 0.35, release: 0.15, sustain: 0.03 },
      gain: 0.14,
      source: { fm: { depth: 120, ratio: 1.5 }, frequency: 1170, type: "sine" },
    },
  ],
};
export const mention: SoundDefinition = {
  effects: [{ type: "reverb", decay: 0.6, damping: 0.5, mix: 0.1 }],
  envelope: { attack: 0.003, decay: 0.5, release: 0.2, sustain: 0.05 },
  gain: 0.14,
  source: { fm: { depth: 150, ratio: 2.5 }, frequency: 660, type: "sine" },
};
export const badge: SoundDefinition = {
  effects: [{ type: "reverb", decay: 0.5, damping: 0.6, mix: 0.1 }],
  envelope: { attack: 0, decay: 0.35, release: 0.15, sustain: 0.04 },
  gain: 0.16,
  source: { fm: { depth: 350, ratio: 2.76 }, frequency: 1100, type: "sine" },
};
export const info: SoundDefinition = {
  envelope: { attack: 0.003, decay: 0.3, release: 0.12, sustain: 0.04 },
  gain: 0.14,
  source: { fm: { depth: 120, ratio: 2 }, frequency: 880, type: "sine" },
};
export const sparkle: SoundDefinition = {
  layers: [
    {
      effects: [{ type: "reverb", decay: 0.8, damping: 0.5, mix: 0.15 }],
      envelope: { attack: 0, decay: 0.4, release: 0.18, sustain: 0.04 },
      gain: 0.12,
      source: {
        detune: 7,
        fm: { depth: 200, ratio: 3.5 },
        frequency: 1047,
        type: "sine",
      },
    },
    {
      envelope: { attack: 0, decay: 0.38, release: 0.18, sustain: 0.03 },
      gain: 0.08,
      source: { fm: { depth: 180, ratio: 3.5 }, frequency: 1050, type: "sine" },
    },
  ],
};
export const star: SoundDefinition = {
  effects: [{ type: "reverb", decay: 0.6, damping: 0.5, mix: 0.12 }],
  envelope: { attack: 0, decay: 0.4, release: 0.18, sustain: 0.04 },
  gain: 0.14,
  source: { fm: { depth: 250, ratio: 2.76 }, frequency: 880, type: "sine" },
};
export const error: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.25, release: 0.08, sustain: 0 },
      filter: { frequency: 1200, type: "lowpass" },
      gain: 0.22,
      source: { frequency: { end: 140, start: 320 }, type: "sawtooth" },
    },
    {
      delay: 0.03,
      envelope: { attack: 0, decay: 0.2, release: 0.06, sustain: 0 },
      filter: { frequency: 800, type: "lowpass" },
      gain: 0.12,
      source: { frequency: { end: 80, start: 180 }, type: "square" },
    },
  ],
};
export const _delete: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.3, release: 0.08, sustain: 0 },
      filter: { frequency: 800, type: "lowpass" },
      gain: 0.18,
      source: { frequency: { end: 100, start: 300 }, type: "sawtooth" },
    },
    {
      delay: 0.02,
      envelope: { attack: 0, decay: 0.25, release: 0.06, sustain: 0 },
      filter: { frequency: 600, type: "lowpass" },
      gain: 0.1,
      source: { frequency: { end: 60, start: 200 }, type: "square" },
    },
  ],
};
export const warning: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.18, release: 0.06, sustain: 0.06 },
      gain: 0.2,
      source: { frequency: 440, type: "triangle" },
    },
    {
      delay: 0.01,
      envelope: { attack: 0, decay: 0.18, release: 0.06, sustain: 0.06 },
      gain: 0.15,
      source: { frequency: 466, type: "triangle" },
    },
  ],
};
export const swoosh: SoundDefinition = {
  envelope: { attack: 0.01, decay: 0.12, release: 0.04, sustain: 0 },
  filter: {
    envelope: { attack: 0.01, decay: 0.08, peak: 4000 },
    frequency: 300,
    resonance: 1.8,
    type: "bandpass",
  },
  gain: 0.12,
  source: { color: "white", type: "noise" },
};
export const whoosh: SoundDefinition = {
  envelope: { attack: 0.02, decay: 0.25, release: 0.08, sustain: 0 },
  filter: {
    envelope: { attack: 0.04, decay: 0.16, peak: 4000 },
    frequency: 300,
    resonance: 1.5,
    type: "bandpass",
  },
  gain: 0.15,
  source: { color: "white", type: "noise" },
};
export const pageEnter: SoundDefinition = {
  envelope: { attack: 0.02, decay: 0.2, release: 0.06, sustain: 0 },
  filter: {
    envelope: { attack: 0.03, decay: 0.15, peak: 3000 },
    frequency: 400,
    resonance: 1.2,
    type: "bandpass",
  },
  gain: 0.08,
  source: { color: "white", type: "noise" },
};
export const pageExit: SoundDefinition = {
  envelope: { attack: 0.01, decay: 0.2, release: 0.06, sustain: 0 },
  filter: {
    envelope: { decay: 0.18, peak: 400 },
    frequency: 2500,
    resonance: 1.2,
    type: "bandpass",
  },
  gain: 0.07,
  source: { color: "pink", type: "noise" },
};
export const tabSwitch: SoundDefinition = {
  envelope: { attack: 0, decay: 0.05, release: 0.015, sustain: 0 },
  gain: 0.18,
  source: {
    fm: { depth: 50, ratio: 0.5 },
    frequency: { end: 1500, start: 1100 },
    type: "sine",
  },
};
export const drawerOpen: SoundDefinition = {
  envelope: { attack: 0, decay: 0.1, release: 0.03, sustain: 0 },
  gain: 0.08,
  source: { frequency: { end: 1000, start: 350 }, type: "sine" },
};
export const drawerClose: SoundDefinition = {
  envelope: { attack: 0, decay: 0.1, release: 0.03, sustain: 0 },
  gain: 0.06,
  source: { frequency: { end: 350, start: 800 }, type: "sine" },
};
export const modalOpen: SoundDefinition = {
  envelope: { attack: 0, decay: 0.08, release: 0.025, sustain: 0 },
  gain: 0.1,
  source: { frequency: { end: 1400, start: 430 }, type: "sine" },
};
export const modalClose: SoundDefinition = {
  envelope: { attack: 0, decay: 0.08, release: 0.025, sustain: 0 },
  gain: 0.08,
  source: { frequency: { end: 430, start: 730 }, type: "sine" },
};
export const dropdownOpen: SoundDefinition = {
  envelope: { attack: 0, decay: 0.06, release: 0.02, sustain: 0 },
  gain: 0.07,
  source: { frequency: { end: 1200, start: 500 }, type: "sine" },
};
export const dropdownClose: SoundDefinition = {
  envelope: { attack: 0, decay: 0.06, release: 0.02, sustain: 0 },
  gain: 0.05,
  source: { frequency: { end: 500, start: 900 }, type: "sine" },
};
export const slide: SoundDefinition = {
  envelope: { attack: 0.01, decay: 0.15, release: 0.05, sustain: 0 },
  filter: {
    envelope: { attack: 0.02, decay: 0.12, peak: 3000 },
    frequency: 500,
    resonance: 1,
    type: "bandpass",
  },
  gain: 0.07,
  source: { color: "white", type: "noise" },
};
export const slideUp: SoundDefinition = {
  envelope: { attack: 0.01, decay: 0.15, release: 0.05, sustain: 0 },
  filter: {
    envelope: { attack: 0.02, decay: 0.12, peak: 3500 },
    frequency: 500,
    resonance: 1,
    type: "bandpass",
  },
  gain: 0.07,
  source: { color: "white", type: "noise" },
};
export const slideDown: SoundDefinition = {
  envelope: { attack: 0.01, decay: 0.15, release: 0.05, sustain: 0 },
  filter: {
    envelope: { decay: 0.12, peak: 500 },
    frequency: 2500,
    resonance: 1,
    type: "bandpass",
  },
  gain: 0.06,
  source: { color: "pink", type: "noise" },
};
export const copy: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.015, release: 0.006, sustain: 0 },
      gain: 0.16,
      source: { frequency: 1200, type: "sine" },
    },
    {
      delay: 0.04,
      envelope: { attack: 0, decay: 0.015, release: 0.006, sustain: 0 },
      gain: 0.14,
      source: { frequency: 1400, type: "sine" },
    },
  ],
};
export const send: SoundDefinition = {
  envelope: { attack: 0, decay: 0.15, release: 0.04, sustain: 0 },
  gain: 0.16,
  source: { frequency: { end: 1200, start: 500 }, type: "sine" },
};
export const receive: SoundDefinition = {
  envelope: { attack: 0, decay: 0.12, release: 0.04, sustain: 0.02 },
  gain: 0.12,
  source: { frequency: { end: 700, start: 1200 }, type: "sine" },
};
export const command: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.05, release: 0.015, sustain: 0 },
      gain: 0.18,
      source: { frequency: { end: 900, start: 600 }, type: "sine" },
    },
    {
      delay: 0.04,
      envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
      gain: 0.12,
      source: { frequency: { end: 1100, start: 900 }, type: "sine" },
    },
  ],
};
export const escape: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.05, release: 0.015, sustain: 0 },
      gain: 0.16,
      source: { frequency: { end: 600, start: 900 }, type: "sine" },
    },
    {
      delay: 0.03,
      envelope: { attack: 0, decay: 0.04, release: 0.012, sustain: 0 },
      gain: 0.1,
      source: { frequency: { end: 500, start: 700 }, type: "sine" },
    },
  ],
};
export const undo: SoundDefinition = {
  envelope: { attack: 0, decay: 0.12, release: 0.04, sustain: 0.02 },
  gain: 0.14,
  source: { frequency: { end: 600, start: 900 }, type: "sine" },
};
export const archive: SoundDefinition = {
  envelope: { attack: 0.003, decay: 0.15, release: 0.05, sustain: 0.02 },
  gain: 0.12,
  source: { frequency: { end: 550, start: 800 }, type: "sine" },
};
export const sync: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.015, release: 0.005, sustain: 0 },
      gain: 0.14,
      source: { frequency: 523, type: "sine" },
    },
    {
      delay: 0.04,
      envelope: { attack: 0, decay: 0.015, release: 0.005, sustain: 0 },
      gain: 0.12,
      source: { frequency: 784, type: "sine" },
    },
  ],
};
export const heart: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.1, release: 0.04, sustain: 0 },
      gain: 0.16,
      source: { frequency: { end: 300, start: 500 }, type: "sine" },
    },
    {
      envelope: { attack: 0.008, decay: 0.25, release: 0.1, sustain: 0.04 },
      gain: 0.1,
      source: { fm: { depth: 100, ratio: 2.5 }, frequency: 523, type: "sine" },
    },
  ],
};
export const streak: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.12, release: 0.05, sustain: 0.02 },
      gain: 0.16,
      source: { frequency: { end: 784, start: 523 }, type: "sine" },
    },
    {
      envelope: { attack: 0, decay: 0.11, release: 0.05, sustain: 0.01 },
      gain: 0.08,
      source: {
        fm: { depth: 100, ratio: 2.5 },
        frequency: { end: 787, start: 526 },
        type: "sine",
      },
    },
  ],
};
export const loadingStart: SoundDefinition = {
  envelope: { attack: 0.008, decay: 0.12, release: 0.05, sustain: 0.02 },
  gain: 0.08,
  source: { frequency: { end: 700, start: 500 }, type: "sine" },
};
export const loadingEnd: SoundDefinition = {
  layers: [
    {
      envelope: { attack: 0, decay: 0.1, release: 0.04, sustain: 0.02 },
      gain: 0.1,
      source: { frequency: { end: 880, start: 700 }, type: "sine" },
    },
    {
      delay: 0.06,
      envelope: { attack: 0, decay: 0.08, release: 0.04, sustain: 0.01 },
      gain: 0.08,
      source: { frequency: { end: 1046, start: 880 }, type: "sine" },
    },
  ],
};
export const progressTick: SoundDefinition = {
  envelope: { attack: 0, decay: 0.01, release: 0.004, sustain: 0 },
  gain: 0.1,
  source: { fm: { depth: 50, ratio: 0.5 }, frequency: 1400, type: "sine" },
};

export const _patch: SoundPatch = {
  name: "Core",
  author: "Raphael Salaja",
  version: "3.1.0",
  description:
    "A foundational UI sound pack with essential clicks, toggles, pops, notifications, and transitions, designed to feel clear and familiar across everyday product interactions without overwhelming the interface.",
  sounds: {
    click,
    tap,
    "key-press": keyPress,
    checkbox,
    radio,
    tick,
    "scroll-snap": scrollSnap,
    focus,
    blur,
    "toggle-on": toggleOn,
    "toggle-off": toggleOff,
    hover,
    select,
    deselect,
    pop,
    boop,
    bounce,
    spring,
    expand,
    collapse,
    success,
    complete,
    "level-up": levelUp,
    confetti,
    save,
    ding,
    notification,
    mention,
    badge,
    info,
    sparkle,
    star,
    error,
    delete: _delete,
    warning,
    swoosh,
    whoosh,
    "page-enter": pageEnter,
    "page-exit": pageExit,
    "tab-switch": tabSwitch,
    "drawer-open": drawerOpen,
    "drawer-close": drawerClose,
    "modal-open": modalOpen,
    "modal-close": modalClose,
    "dropdown-open": dropdownOpen,
    "dropdown-close": dropdownClose,
    slide,
    "slide-up": slideUp,
    "slide-down": slideDown,
    copy,
    send,
    receive,
    command,
    escape,
    undo,
    archive,
    sync,
    heart,
    streak,
    "loading-start": loadingStart,
    "loading-end": loadingEnd,
    "progress-tick": progressTick,
  },
};
