export const ROUTES = {
  AGENT_SKILLS_INDEX: "/.well-known/agent-skills/index.json",
  AGENT_SKILLS_SITE_SKILL: "/.well-known/agent-skills/site-skill.md",
  API_CATALOG: "/.well-known/api-catalog",
  API_STATUS: "/api/status",
  DOCS: "/docs",
  DOCS_ASSETS: "/docs/assets",
  DOCS_CHANGELOG: "/docs/changelog",
  DOCS_COMPONENTS: "/docs/components",
  DOCS_COMPONENTS_GPUI: "/docs/components/gpui",
  DOCS_GETTING_STARTED: "/docs/getting-started",
  DOCS_THEME: "/docs/theme",
  HOME: "/",
  LLMS: "/llms.txt",
  LLMS_FULL: "/llms-full.txt",
  LLMS_MD: "/llms.md",
  MANIFEST: "/manifest.webmanifest",
  OG: "/og",
  OPENAPI: "/openapi.json",
  ROBOTS: "/robots.txt",
  RSS: "/rss.xml",
  SITEMAP: "/sitemap.xml",
  SPONSOR: "/sponsor",
} as const;
